### ISSUE TITLE
Assign LDAP user to a connection or connection group

### ISSUE THREAD

**Issue by tm3codefire** [UpperM/guacamole-powershell#12]
i knew this scripts are just made for mysql users in guacamole.
we have connected the ldap for authentication to guacamole to have same users and passwords for access.

with your cmdlets we could now provide automatically a new connection to a RDP Host (and delete it too). THX

now i still missing how we can add a ldap user to a connection or user-group stored in mysql (generated over your cmdlets)

**Comment by UpperM** [comment]
Hi,

You need to create yours users in Guacamole but dont provide password when your create user. 

When your user logged in, Guacamole will reach your Active Directory to made the authentication (because no password set in user profile)

Bonus, if you want SSO with RDP

Hi,
I also use LDAP for SSO with RDP :

1. Create your ldap user in Guacamole with only de login field (for me its the userPrincipalName). Do not provide password
2. Create your RDP connection :
      In Authentication, provide theses settings : 
           Username : ${GUAC_USERNAME}
           Password : ${GUAC_PASSWORD}
4. Then assign connection to your user

Your user can now logged with his LDAP credentials and the RDP will use his authentication informations to connect.
